# Site settings
title: Techgist - TechEasy by TechieZee
email: zaidi.zeeshan@outlook.com
description: A blog about my favorite web technologies.
url: "https://zaidizeeshan.github.io" # the base hostname & protocol for your site
twitter_username: zaidizeeshan
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Zeeshan Zaidi
      layout: "post"
      category: conferences
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"





